### ISSUE TITLE
SDCC build issues?

### ISSUE THREAD

**Issue by Flameeyes** [kenyapcomau/QX-mini51-SDCC#1]
Hello! I'm finding myself fighting with a strange ghost with my STC89 not responding to my programs, that used to work perfectly fine (on a 4.3C revision), now I've tried re-flashing the micro with one of those programs, and it doesn't seem to initialize correctly at all.

I tried one of your samples (`02-marquee`) and it also doesn't seem to work, in the same way. I tried in-system programming as well as on the separate board, and both appear to have the same issues.

Any chance you can share which version of sdcc you're using, or a pre-built IHX, so I can check if I have something broken on my programmer? If you prefer contacting me off-github, I'm flameeyes@flameeyes.com

**Comment by kenyapcomau** [comment]
The SDCC version I used is 3.9. Note that these programs will probably only work on the dev board I have due to the circuit and port assignments. If you have a different dev board, you have to adapt the programs.
